# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/form_simple.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frmMain = QtWidgets.QFrame(self.centralwidget)
        self.frmMain.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.frmMain.setObjectName("frmMain")
        self.frmSettings = QtWidgets.QFrame(self.frmMain)
        self.frmSettings.setGeometry(QtCore.QRect(0, 0, 1024, 524))
        self.frmSettings.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frmSettings.setObjectName("frmSettings")
        self.scrollSettings = QtWidgets.QScrollArea(self.frmSettings)
        self.scrollSettings.setGeometry(QtCore.QRect(20, 80, 981, 441))
        self.scrollSettings.setStyleSheet("background-color: rgb(20, 20, 20);")
        self.scrollSettings.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollSettings.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollSettings.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollSettings.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollSettings.setWidgetResizable(True)
        self.scrollSettings.setObjectName("scrollSettings")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 967, 441))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vlytSettings = QtWidgets.QVBoxLayout()
        self.vlytSettings.setObjectName("vlytSettings")
        self.horizontalLayout.addLayout(self.vlytSettings)
        self.scrollSettings.setWidget(self.scrollAreaWidgetContents)
        self.lblSettingsTitle = QtWidgets.QLabel(self.frmSettings)
        self.lblSettingsTitle.setGeometry(QtCore.QRect(20, 20, 461, 51))
        self.lblSettingsTitle.setStyleSheet(
            "color: rgb(130, 130, 130);\n"
            "font: 22pt \"Orbitron\";")
        self.lblSettingsTitle.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.lblSettingsTitle.setObjectName("lblSettingsTitle")
        self.frmHome = QtWidgets.QFrame(self.frmMain)
        self.frmHome.setGeometry(QtCore.QRect(0, 0, 1024, 524))
        self.frmHome.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frmHome.setObjectName("frmHome")
        self.lblDate = QtWidgets.QLabel(self.frmHome)
        self.lblDate.setGeometry(QtCore.QRect(417, 320, 190, 40))
        self.lblDate.setStyleSheet(
            "color: rgb(255, 255, 255);\n"
            "font: 18pt \"Wallpoet\";")
        self.lblDate.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.lblDate.setObjectName("lblDate")
        self.lblCircle = QtWidgets.QLabel(self.frmHome)
        self.lblCircle.setGeometry(QtCore.QRect(318, 106, 388, 388))
        self.lblCircle.setStyleSheet(
            "border: 8px solid yellow;\n"
            "border-radius: 194;\n"
            "background-color: black;")
        self.lblCircle.setObjectName("lblCircle")
        self.lblTime = QtWidgets.QLabel(self.frmHome)
        self.lblTime.setGeometry(QtCore.QRect(336, 250, 350, 70))
        font = QtGui.QFont()
        font.setFamily("Wallpoet")
        font.setPointSize(44)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblTime.setFont(font)
        self.lblTime.setStyleSheet(
            "color: rgb(255, 255, 255);\n"
            "font: 44pt \"Wallpoet\";")
        self.lblTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTime.setObjectName("lblTime")
        self.lblCircle.raise_()
        self.lblTime.raise_()
        self.lblDate.raise_()
        self.lblName = QtWidgets.QLabel(self.frmMain)
        self.lblName.setGeometry(QtCore.QRect(20, 550, 181, 41))
        self.lblName.setStyleSheet(
            "font: 14pt \"Orbitron\";\n"
            "color: rgb(128, 128, 128);")
        self.lblName.setObjectName("lblName")
        self.btnSettings = QtWidgets.QPushButton(self.frmMain)
        self.btnSettings.setGeometry(QtCore.QRect(850, 530, 71, 51))
        self.btnSettings.setStyleSheet(
            "background-color: rgb(30, 30, 30); \n"
            "border: 1px solid rgb(90,90,90);\n"
            "border-radius: 4px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("design/resources/images/tools-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSettings.setIcon(icon)
        self.btnSettings.setIconSize(QtCore.QSize(36, 36))
        self.btnSettings.setFlat(True)
        self.btnSettings.setObjectName("btnSettings")
        self.btnHome = QtWidgets.QPushButton(self.frmMain)
        self.btnHome.setGeometry(QtCore.QRect(770, 530, 71, 51))
        self.btnHome.setStyleSheet(
            "background-color: rgb(30, 30, 30); \n"
            "border: 1px solid rgb(90,90,90);\n"
            "border-radius: 4px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("design/resources/images/home-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHome.setIcon(icon1)
        self.btnHome.setIconSize(QtCore.QSize(36, 36))
        self.btnHome.setFlat(True)
        self.btnHome.setObjectName("btnHome")
        self.btnCams = QtWidgets.QPushButton(self.frmMain)
        self.btnCams.setGeometry(QtCore.QRect(930, 530, 71, 51))
        self.btnCams.setStyleSheet(
            "background-color: rgb(30, 30, 30); \n"
            "border: 1px solid rgb(90,90,90);\n"
            "border-radius: 4px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("design/resources/images/camera-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCams.setIcon(icon2)
        self.btnCams.setIconSize(QtCore.QSize(36, 36))
        self.btnCams.setFlat(True)
        self.btnCams.setObjectName("btnCams")
        self.frmCams = QtWidgets.QFrame(self.frmMain)
        self.frmCams.setGeometry(QtCore.QRect(0, 0, 1024, 524))
        self.frmCams.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frmCams.setObjectName("frmCams")
        self.scrollCams = QtWidgets.QScrollArea(self.frmCams)
        self.scrollCams.setGeometry(QtCore.QRect(20, 80, 981, 441))
        self.scrollCams.setStyleSheet("background-color: rgb(20, 20, 20);")
        self.scrollCams.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollCams.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollCams.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollCams.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollCams.setWidgetResizable(True)
        self.scrollCams.setObjectName("scrollCams")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 967, 441))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.glytCams = QtWidgets.QGridLayout()
        self.glytCams.setContentsMargins(0, 8, 0, 8)
        self.glytCams.setSpacing(20)
        self.glytCams.setObjectName("glytCams")
        self.gridLayout_2.addLayout(self.glytCams, 0, 0, 1, 1)
        self.scrollCams.setWidget(self.scrollAreaWidgetContents_2)
        self.lblCamsTitle = QtWidgets.QLabel(self.frmCams)
        self.lblCamsTitle.setGeometry(QtCore.QRect(20, 20, 461, 51))
        self.lblCamsTitle.setStyleSheet(
            "color: rgb(130, 130, 130);\n"
            "font: 22pt \"Orbitron\";")
        self.lblCamsTitle.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.lblCamsTitle.setObjectName("lblCamsTitle")
        self.frmCamsViewer = QtWidgets.QFrame(self.frmMain)
        self.frmCamsViewer.setGeometry(QtCore.QRect(0, 0, 1024, 524))
        self.frmCamsViewer.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frmCamsViewer.setObjectName("frmCamsViewer")
        self.lblCamsViewerTitle = QtWidgets.QLabel(self.frmCamsViewer)
        self.lblCamsViewerTitle.setGeometry(QtCore.QRect(20, 20, 461, 51))
        self.lblCamsViewerTitle.setStyleSheet(
            "color: rgb(130, 130, 130);\n"
            "font: 22pt \"Orbitron\";")
        self.lblCamsViewerTitle.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.lblCamsViewerTitle.setObjectName("lblCamsViewerTitle")
        self.lblVideo = QtWidgets.QLabel(self.frmCamsViewer)
        self.lblVideo.setGeometry(QtCore.QRect(20, 80, 981, 441))
        self.lblVideo.setStyleSheet(
            "background-color: rgb(20, 20, 20);\n"
            "border: 1px solid rgb(90,90,90);")
        self.lblVideo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblVideo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblVideo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblVideo.setObjectName("lblVideo")
        self.lblName.raise_()
        self.btnSettings.raise_()
        self.btnCams.raise_()
        self.frmCamsViewer.raise_()
        self.btnHome.raise_()
        self.frmHome.raise_()
        self.frmSettings.raise_()
        self.frmCams.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.lblSettingsTitle.setText(_translate("MainWindow", "Settings"))
        self.lblDate.setText(_translate("MainWindow", "Tue, Aug 3"))
        self.lblTime.setText(_translate("MainWindow", "12:00 PM"))
        self.lblName.setText(_translate("MainWindow", "K-REN 0702021"))
        self.lblCamsTitle.setText(_translate("MainWindow", "Cams"))
        self.lblCamsViewerTitle.setText(_translate("MainWindow", "Cams: Viewer"))
