# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/settings_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeviceItem(object):
    def setupUi(self, DeviceItem):
        DeviceItem.setObjectName("DeviceItem")
        DeviceItem.resize(965, 70)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DeviceItem.sizePolicy().hasHeightForWidth())
        DeviceItem.setSizePolicy(sizePolicy)
        DeviceItem.setMinimumSize(QtCore.QSize(0, 70))
        self.frame = QtWidgets.QFrame(DeviceItem)
        self.frame.setGeometry(QtCore.QRect(0, 0, 965, 70))
        self.frame.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.frame.setObjectName("frame")
        self.device = QtWidgets.QLabel(self.frame)
        self.device.setGeometry(QtCore.QRect(210, 0, 321, 31))
        self.device.setStyleSheet(
            "font-size: 14pt;\n"
            "color: rgb(255, 255, 255);\n"
            "font-weight: bold;")
        self.device.setObjectName("device")
        self.accepts = QtWidgets.QLabel(self.frame)
        self.accepts.setGeometry(QtCore.QRect(550, 10, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.accepts.setFont(font)
        self.accepts.setStyleSheet("color: rgb(255, 255, 255);")
        self.accepts.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.accepts.setWordWrap(True)
        self.accepts.setObjectName("accepts")
        self.id = QtWidgets.QLabel(self.frame)
        self.id.setGeometry(QtCore.QRect(210, 22, 321, 31))
        self.id.setStyleSheet(
            "font-size: 10pt;\n"
            "color: rgb(100,100,100);")
        self.id.setObjectName("id")
        self.version = QtWidgets.QLabel(self.frame)
        self.version.setGeometry(QtCore.QRect(210, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.version.setFont(font)
        self.version.setStyleSheet("color: rgb(255, 255, 255);")
        self.version.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.version.setObjectName("version")
        self.container = QtWidgets.QLabel(self.frame)
        self.container.setGeometry(QtCore.QRect(10, 2, 181, 31))
        self.container.setStyleSheet("color: rgb(255, 255, 255);")
        self.container.setObjectName("container")
        self.groupName = QtWidgets.QLabel(self.frame)
        self.groupName.setGeometry(QtCore.QRect(10, 30, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupName.setFont(font)
        self.groupName.setStyleSheet("color:rgb(186, 189, 182);")
        self.groupName.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.groupName.setObjectName("groupName")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(820, 10, 131, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vlytSwitch = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vlytSwitch.setContentsMargins(0, 0, 0, 0)
        self.vlytSwitch.setObjectName("vlytSwitch")
        self.accepts.raise_()
        self.id.raise_()
        self.version.raise_()
        self.container.raise_()
        self.groupName.raise_()
        self.verticalLayoutWidget.raise_()
        self.device.raise_()

        self.retranslateUi(DeviceItem)
        QtCore.QMetaObject.connectSlotsByName(DeviceItem)

    def retranslateUi(self, DeviceItem):
        _translate = QtCore.QCoreApplication.translate
        DeviceItem.setWindowTitle(_translate("DeviceItem", "Form"))
        self.device.setText(_translate("DeviceItem", "kenzy_listener.Listener"))
        self.accepts.setText(_translate("DeviceItem", "stop, stopDevices, status"))
        self.id.setText(_translate("DeviceItem", "1a01692c-74bc-4ed7-9e9e-1b338733cb56"))
        self.version.setText(_translate("DeviceItem", "v0.7.0"))
        self.container.setText(_translate("DeviceItem", "http://localhost:8081"))
        self.groupName.setText(_translate("DeviceItem", "Living Room"))
